### ISSUE TITLE
Test Script for videos

### ISSUE THREAD

**Issue by xxiMiaxx** [sauradip/STALE#10]
Dear authors, 

Thank you for the amazing work. 

is there a test script we can use to test on any random video? I've noticed that inference and validation are mostly for a predefined benchmark. 

Thank you.

**Comment by sauradip** [comment]
Hi, thanks for the interest. We will try for a benchmark soon. Since it requires frame by frame feature extraction for any custom video, we opted out. But we will add after ICCV deadline

**Comment by xxiMiaxx** [comment]
Thank you, looking forward to seeing your work!
