### ISSUE TITLE
 The support for THUMOS14 dataset.

### ISSUE THREAD

**Issue by wanghao15536870732** [sauradip/STALE#15]
Can you provide a data loader for the THUMOS14 dataset?

**Comment by sauradip** [comment]
You can follow this repository for this dataset. I have followed this , my current code is not polished yet to make it public.

https://github.com/TencentYoutuResearch/ActionDetection-AFSD/blob/ed86a0df91e58baa7d78c796ed29cff82b1f3fa6/AFSD/common/thumos_dataset.py

**Comment by wanghao15536870732** [comment]
Thank you very much, this has helped me a lot.
