### ISSUE TITLE
Question about video num of Anet datasets

### ISSUE THREAD

**Issue by Neptunelover** [sauradip/STALE#6]
Nice work, thanks for your publication!

I noticed that the number of Anet I3D feature is not consistent with the video number (about 20k). Why is there difference?

**Comment by wmc12138** [comment]
> Nice work, thanks for your publication!
> 
> I noticed that the number of Anet I3D feature is not consistent with the video number (about 20k). Why is there difference?

Hello, I have the same problem as you. I download Anet CLIP feature and find it only has 14376 npy files. How many npy files do you download？
