### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by akshitac8** [sauradip/STALE#7]
Hello @sauradip Can you please share the training details for the code?

**Comment by sauradip** [comment]
The training time is approximately 1-2 hr at maximum. We freeze the vision encoder and fine-tune only the task specific modules.

**Comment by sauradip** [comment]
Please find it here : [https://drive.google.com/file/d/1UmgUV80XINOqKVk-uuF6JcENN6_wb_2f/view?usp=share_link](50-50 Checkpoint)
